language: r
cache: packages
latex: false
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --ignore-vignettes

r_packages:
  - covr
  
env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
