init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

branches:
  only:
    - master

install:
  ps: Bootstrap

environment:
  global:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    _R_CHECK_FORCE_SUGGESTS_: true
    USE_RTOOLS: yes
    WARNINGS_ARE_ERRORS: 
    R_VERSION: release
    R_ARCH: x64
    R_CHECK_ARGS: --as-cran --no-manual

build_script:
  - R -e install.packages(c('devtools','testthat','matrixStats','mixsqp','reshape','ggplot2','crayon','microbenchmark','knitr','rmarkdown','L0Learn','Rfast'),head(.libPaths(),1),'http://cran.wustl.edu')
  - travis-tool.sh install_deps
  
test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
